# -*- coding: utf-8 -*-
"""Clase_JuegosLogicos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mprMzAfMEYybESYQNiHDVk2oG7SSE-Wy
"""

# Juego de trivia

preguntas = [
    {
        "pregunta": "¿Cuál es el océano más grande del mundo?",
        "opciones": ["1. Atlántico", "2. Pacífico", "3. Índico", "4. Ártico"],
        "respuesta_correcta": "2"
    },
    {
        "pregunta": "¿Qué país es conocido como la tierra del sol naciente?",
        "opciones": ["1. Japón", "2. China", "3. Corea", "4. India"],
        "respuesta_correcta": "1"
    },
    {
        "pregunta": "¿Cuál es el planeta más cercano al sol?",
        "opciones": ["1. Venus", "2. Marte", "3. Mercurio", "4. Júpiter"],
        "respuesta_correcta": "3"
    }
]

puntaje = 0

print("Bienvenido a la trivia. Responde las siguientes preguntas:\n")

for idx, pregunta in enumerate(preguntas):
    print(f"Pregunta {idx + 1}: {pregunta['pregunta']}")
    for opcion in pregunta["opciones"]:
        print(opcion)

    respuesta = input("Escribe el número de la respuesta correcta: ")

    if respuesta == pregunta["respuesta_correcta"]:
        print("¡Correcto!\n")
        puntaje += 1
    else:
        print(f"Incorrecto. La respuesta correcta era {pregunta['respuesta_correcta']}.\n")

print(f"Juego terminado. Tu puntaje final es: {puntaje} de {len(preguntas)}.")

import random
import time

# Lista de teclas posibles
teclas = ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l']

# Función para medir el tiempo de reacción
def mide_tiempo_respuesta(tecla):
    print(f"¡Presiona la tecla '{tecla}' lo más rápido que puedas!")
    inicio = time.time()  # Marca el tiempo de inicio
    respuesta = input(">>> ")
    fin = time.time()  # Marca el tiempo de fin

    if respuesta == tecla:
        tiempo_reaccion = fin - inicio
        print(f"¡Correcto! Tu tiempo de reacción fue: {tiempo_reaccion:.2f} segundos.")
        return tiempo_reaccion
    else:
        print("Tecla incorrecta. ¡Inténtalo de nuevo!")
        return None

# Juego principal
tiempos = []
intentos = 5  # Número de rondas del juego

print("¡Bienvenido al juego de reflejos!\n")

for i in range(intentos):
    tecla_aleatoria = random.choice(teclas)
    tiempo = mide_tiempo_respuesta(tecla_aleatoria)

    if tiempo:
        tiempos.append(tiempo)

if tiempos:
    promedio_tiempo = sum(tiempos) / len(tiempos)
    print(f"\nJuego terminado. Tu tiempo de reacción promedio fue: {promedio_tiempo:.2f} segundos.")
else:
    print("No lograste acertar ninguna tecla a tiempo.")

print("¡Gracias por jugar!")