# -*- coding: utf-8 -*-
"""Clase Ahorcado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQvhafGRvSXSZzpajyzIC8bnWk4s75g1
"""

import random
from IPython.display import clear_output

DB = [ "DISNEY", "NETFLIX", "MAX", "PRIME"]

# hangman ascii art

Images= HANGMANPICS = ['''
  +---+
  |   |
      |
      |
      |
      |
=========''', '''
  +---+
  |   |
  O   |
      |
      |
      |
=========''', '''
  +---+
  |   |
  O   |
  |   |
      |
      |
=========''', '''
  +---+
  |   |
  O   |
 /|   |
      |
      |
=========''', '''
  +---+
  |   |
  O   |
 /|\  |
      |
      |
=========''', '''
  +---+
  |   |
  O   |
 /|\  |
 /    |
      |
=========''', '''
  +---+
  |   |
  O   |
 /|\  |
 / \  |
      |
=========''']

word = random.choice(DB)

spaces = ["_"] * len(word)

attemps= 0
lifes=6

while True:
  clear_output(wait=True)
  if lifes > 1:
    print("Te quedan",lifes, "vidas")
  else:
    print("Cuidado, te queda",lifes, "sola vida")
  for character in spaces:
    print(character, end=" ")

  print(Images[attemps])
  letter = input("Elige una letra:").upper()

  found = False

  for idx, character in enumerate(word):
    if character == letter:
      spaces[idx] = letter
      found = True

  if not found:
    attemps += 1
    lifes-=1

  if "_" not in spaces:
    clear_output()
    print("¡Ganaste!, la palabra era: ", word)
    break
    input()

  if attemps == 6:
    clear_output()
    print("Perdiste, te quedaste sin intentos... La palabra era:", word)
    break
    input()